"""add closed_at to Task

Revision ID: 396d31a17c37
Revises: 1fe07c87f83e
Create Date: 2025-11-26 17:14:36.857815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396d31a17c37'
down_revision: Union[str, Sequence[str], None] = '1fe07c87f83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'closed_at')
    # ### end Alembic commands ###
