"""feat: fix project names for tasks when a project name updates

Revision ID: 5d1a051355aa
Revises: 76a1b4dab618
Create Date: 2025-11-25 17:42:38.217934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1a051355aa'
down_revision: Union[str, Sequence[str], None] = '76a1b4dab618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_project_name_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_project_name_fkey'), 'tasks', 'projects', ['project_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###
